ShakespeareWeb/Models/SearchQueryFormData.cs
namespace ShakespeareWeb.Models
{
    public class SearchQueryFormData
    {
        public string Keywords { get; set; }
    }
}

ShakespeareWeb/Models/Work.cs
namespace ShakespeareWeb.Models
{
    public class Work
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
    }
}

ShakespeareWeb/Controllers/SearchController.cs
using System.Linq;
using System.Web.Mvc;
using ShakespeareWeb.Services;

namespace ShakespeareWeb.Controllers
{
    public class SearchController : Controller
    {
        private readonly ISearchService _searchService;

        public SearchController(ISearchService searchService)
        {
            _searchService = searchService;
        }

        [HttpGet]
        public ActionResult Index(string keywords)
        {
            if (string.IsNullOrEmpty(keywords))
                return View("NoResults");

            var model = _searchService.SearchByKeyword(Server.HtmlEncode(keywords));

            return (model.Any())
                       ? View(model)
                       : View("NoResults");
        }

    }
}

ShakespeareWeb/Controllers/WorksController.cs
using System.Web.Mvc;
using ShakespeareWeb.Services;

namespace ShakespeareWeb.Controllers
{
    public class WorksController : Controller
    {
        private readonly IWorksService _service;

        public WorksController(IWorksService service)
        {
            _service = service;
        }

        public ActionResult Index()
        {
            return View(_service.GetAllWorks());
        }

        public ActionResult Detail(int id)
        {
            return View(_service.GetById(id));
        }

        [HttpGet]
        public ActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(string keywords)
        {
            return View((keywords));
        }
    }
}

ShakespeareWeb/Views/Search/Index.cshtml
@model IEnumerable<ShakespeareWeb.Models.Work>

@{
    ViewBag.Title = "ShakespeareWeb - Search";
    Html.RenderPartial("_SearchForm");
}

<h2>Search Results</h2>
<ul class="workSummaryList">
@foreach (var item in Model)
{
    <li>
        @Html.ActionLink(item.Title, "Detail", "Works",new {id=item.Id}, null)
    </li>
}
</ul>

ShakespeareWeb/Views/Search/NoResults.cshtml
@model IEnumerable<ShakespeareWeb.Models.Work>

@{
    ViewBag.Title = "ShakespeareWeb - Search";
    Html.RenderPartial("_SearchForm");
}

<h2>Search Results</h2>
<p>Your search did not return any results.</p>

ShakespeareWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/css")" rel="stylesheet" type="text/css" />
    <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/themes/base/css")" rel="stylesheet" type="text/css" />
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Scripts/js")"></script>
</head>
<body>
    @RenderBody()
</body>
</html>

ShakespeareWeb/Views/Shared/_SearchForm.cshtml
<div class="navigation">
    @{ Html.BeginForm("Index", "Search",FormMethod.Get); }
    @Html.ActionLink("Back to Main List", "Index","Works") | 
    
    Search: 
    @Html.TextBox("keywords")
    <input type="submit" name="Search" id="Search" value="Go!" />
    @{
        Html.EndForm();
    }
</div>

ShakespeareWeb/Views/Works/Detail.cshtml
@model ShakespeareWeb.Models.Work

@{
    ViewBag.Title = "ShakespeareWeb - " + Model.Title;
    Html.RenderPartial("_SearchForm");
}

<p class="heading">@Model.Title</p>
<pre class="workText">@Model.Text</pre>

ShakespeareWeb/Views/Works/Index.cshtml
@model IEnumerable<ShakespeareWeb.Models.Work>

@{
    ViewBag.Title = "ShakespeareWeb - Home";
    Html.RenderPartial("_SearchForm");
}

<p class="heading">The Complete Works of William Shakespeare</p>

<ul class="workSummaryList">
@foreach (var item in Model)
{
    <li>
    @Html.ActionLink(item.Title, "Detail", new {id=item.Id})
    </li>
}
</ul>